% This code solves the Ito-form Fokker-Planck equation
%   f_t = -div(F_tilde*f) + div div(D_tilde*f) + R[f],
% where the drift F_tilde used here corresponds to the Ito drift b in the manuscript.
%
% Initial data files generated by initializationsetting.m:
%   f0.dat: the full steady-state initial density.
%   f_left.dat, f_right.dat: normalized left/right basin initial densities.
%   x_saddle_initial.dat: the initial saddle point used to split P/S basins.
%
% Flags:
%   0: R0[f] = 0.
%   1: Rbar[f].
%   2: Rfull[f].
%   3: beta^{*} Rbar[f].
%
% Figure 2 data generation:
%   Panel b:
%     Run Flag=0 from f0.dat with MD.stopMode = 'time';
%     copy the f output to result_fig.2/output_b.
%
%   Panels c,d:
%     Run Flag=0,1,2 from f0.dat with MD.stopMode = 'steady';
%     copy the f outputs to result_fig.2/output_c and result_fig.2/output_d.
%
%   Panel e:
%     Run Flag=1,2 from f0.dat with MD.stopMode = 'steady';
%     copy the Rf outputs to result_fig.2/output_e.
%
%   Panel f:
%     Run Flag=0,1,2 from f_left.dat and f_right.dat with
%     MD.stopMode = 'time'; add _left/_right suffixes, copy the outputs to
%     result_fig.2/output_f, then run compute_P_proportion_data().
%
%   Panel g:
%     Run Flag=2 from f_right.dat; add the _right suffix and copy outputs
%     to result_fig.2/output_g.

%Supplementary Figure S4:
%   Use the same simulations as Figure 2 panel f:
%     Flag=0,1,2 from f_left.dat and f_right.dat with MD.stopMode = 'time'.
%   Copy the _left/_right outputs to result_fig.2/output_f, then run
%   result_fig.2/figure2_f_dataanalysis.m. Figures are saved in
%   result_fig.2/result_fig.S4.
%
% Supplementary Figure S5:
%   Run Flag=0,1,2 from f_left.dat and f_right.dat with MD.T = 30000 and
%   MD.stopMode = 'time'. Add _left/_right suffixes, copy the outputs to
%   result_fig.2/output_h, then run result_fig.2/dataanalysis_h.m.
%   Figures are saved in result_fig.2/result_fig.S5.
%
% Supplementary Figures S1-S3:
%   Upwind_figure:
%     Run Flag=4 and copy outputs to result_fig.S1-S3/output_Upwind.
%
%   U_kappa:
%     Run Flag=2 with l=1:5 and MD.stopMode = 'steady';
%     par.kappa0 = [0, 0.1, 0.2, 0.3, 0.4].
%     copy outputs to result_fig.S1-S3/output_kappa.
%
%   U_beta:
%     Run Flag=2 with l=1:5 and MD.stopMode = 'steady';
%     par.betabar = [0, 0.01, 0.02, 0.03, 0.04].
%     copy outputs to result_fig.S1-S3/output_beta.
%
%   S1_pssi:
%     Run Flag=3 with l=1:3 and MD.stopMode = 'steady';
%     par.pssi0 = [0.1, 0.9, 0.1], and
%     par.pssi1 = [1.4, 1.4, 0.85].;
%     copy outputs to result_fig.S1-S3/output_pssi.

function main()
tic

global MD D1 F1

Control();
parameter();
MD.dx = 0.005;
MD.n=size(0:MD.dx:MD.xmax,2)-1;  % MD.n = n
MD.stopMode = 0; 
F1 = F_tilde_function();    
D1 = D_tilde_function();
initialf = 'Initf/f0-2.dat';
f0 = Initializationf(initialf);

for k = 0:2
    Flag = k;
    path = strcat('output/R',num2str(k),'/');

    [Ff, Fq, Fqsum, FRf] = Solve_Equation(Flag, f0);

    dlmwrite(strcat(path, 'md-',num2str(Flag),'-f.dat'), Ff,    ' ');
    dlmwrite(strcat(path, 'md-',num2str(Flag),'-Q.dat'), Fq,    ' ');
    dlmwrite(strcat(path, 'md-',num2str(Flag),'-Qsum.dat'), Fqsum, ' ');
    dlmwrite(strcat(path, 'md-',num2str(Flag),'-Rf.dat'), FRf,   ' ');

end
toc
end

